schema:
  - "http://localhost:54321/graphql/v1"
documents:
  - "./graphql/{queries,mutations}.graphql"
generates:
  ./graphql/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
