schema:
  - "http://localhost:54321/graphql/v1"
documents:
  - "./api/graphql/{queries,mutations}.graphql"
generates:
  ./api/graphql/generated/graphql.ts:
    config:
      - skipTypename: true
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
