import Header from "./_components/header"
import Footer from "./_components/footer"
import { ApolloWrapper } from "../api/apollo/apollo-wrapper"

import "./_styles/reset.css"
import "./_styles/globals.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <ApolloWrapper>
          <Header />
          <div className="p-5 md:py-8 md:px-32">{children}</div>
          <Footer />
        </ApolloWrapper>
      </body>
    </html>
  )
}
