drop policy "Enable read access for all users" on "public"."makers";

drop policy "Enable read access for all users" on "public"."proteins";

drop policy "Enable read access for all users" on "public"."reviews";

alter table "public"."makers" drop constraint "maker_pkey";

alter table "public"."reviews" drop constraint "reviews_pkey";

alter table "public"."proteins" drop constraint "proteins_pkey";

drop index if exists "public"."maker_pkey";

drop index if exists "public"."reviews_pkey";

drop index if exists "public"."proteins_pkey";

drop table "public"."reviews";

create table "public"."レビュー" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null default ''::text,
    "rate" numeric not null default '0'::numeric,
    "title" text not null default ''::text,
    "description" text not null,
    "protein_id" bigint not null
);


alter table "public"."レビュー" enable row level security;

alter table "public"."makers" alter column "created_at" set not null;

alter table "public"."makers" alter column "name" set default ''::text;

alter table "public"."makers" alter column "src" set not null;

alter table "public"."proteins" drop column "review_id";

alter table "public"."proteins" alter column "created_at" set not null;

CREATE UNIQUE INDEX makers_id_key ON public.makers USING btree (id);

CREATE UNIQUE INDEX makers_pkey ON public.makers USING btree (id);

CREATE UNIQUE INDEX proteins_id_key ON public.proteins USING btree (id);

CREATE UNIQUE INDEX "レビュー_id_key" ON public."レビュー" USING btree (id);

CREATE UNIQUE INDEX "レビュー_pkey" ON public."レビュー" USING btree (id);

CREATE UNIQUE INDEX proteins_pkey ON public.proteins USING btree (id);

alter table "public"."makers" add constraint "makers_pkey" PRIMARY KEY using index "makers_pkey";

alter table "public"."レビュー" add constraint "レビュー_pkey" PRIMARY KEY using index "レビュー_pkey";

alter table "public"."proteins" add constraint "proteins_pkey" PRIMARY KEY using index "proteins_pkey";

alter table "public"."makers" add constraint "makers_id_key" UNIQUE using index "makers_id_key";

alter table "public"."makers" add constraint "makers_protein_id_fkey" FOREIGN KEY (protein_id) REFERENCES proteins(id) not valid;

alter table "public"."makers" validate constraint "makers_protein_id_fkey";

alter table "public"."proteins" add constraint "proteins_id_key" UNIQUE using index "proteins_id_key";

alter table "public"."proteins" add constraint "proteins_maker_id_fkey" FOREIGN KEY (maker_id) REFERENCES makers(id) ON DELETE CASCADE not valid;

alter table "public"."proteins" validate constraint "proteins_maker_id_fkey";

alter table "public"."レビュー" add constraint "レビュー_id_key" UNIQUE using index "レビュー_id_key";

alter table "public"."レビュー" add constraint "レビュー_protein_id_fkey" FOREIGN KEY (protein_id) REFERENCES proteins(id) ON DELETE CASCADE not valid;

alter table "public"."レビュー" validate constraint "レビュー_protein_id_fkey";


