alter table "public"."flavors " drop constraint "flavors _product_id_fkey";

alter table "public"."flavors " drop constraint "flavors _protein_id_fkey";

alter table "public"."flavors " drop constraint "flavors _purchase_link_id_fkey";

alter table "public"."flavors " drop constraint "flavors _review_id_fkey";

alter table "public"."makers" drop constraint "makers_id_key";

alter table "public"."purchase_links" drop constraint "purchase_links_flavor_id_fkey";

alter table "public"."products" drop constraint "products_flavor_id_fkey";

alter table "public"."proteins" drop constraint "proteins_flavor_id_fkey";

alter table "public"."reviews" drop constraint "reviews_flavor_id_fkey";

alter table "public"."flavors " drop constraint "flavors _pkey";

alter table "public"."proteins" drop constraint "proteins_pkey";

alter table "public"."purchase_links" drop constraint "purchase_links_pkey";

drop index if exists "public"."flavors _pkey";

drop index if exists "public"."makers_id_key";

drop index if exists "public"."proteins_pkey";

drop index if exists "public"."purchase_links_pkey";

drop table "public"."flavors ";

drop table "public"."purchase_links";

create table "public"."flavors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null default ''::text,
    "src" text not null default ''::text,
    "protein_id" bigint not null,
    "seller_id" bigint,
    "product_id" bigint,
    "review_id" bigint
);


alter table "public"."flavors" enable row level security;

create table "public"."sellers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "official" text not null default ''::text,
    "amazon" text default ''::text,
    "rakuten" text default ''::text,
    "yahoo" text default ''::text,
    "flavor_id" bigint
);


alter table "public"."sellers" enable row level security;

alter table "public"."makers" alter column "src" set default ''::text;

alter table "public"."makers" enable row level security;

alter table "public"."products" alter column "price" drop default;

alter table "public"."products" alter column "price" set data type bigint using "price"::bigint;

alter table "public"."products" enable row level security;

alter table "public"."proteins" enable row level security;

alter table "public"."reviews" enable row level security;

CREATE UNIQUE INDEX flavor_pkey ON public.flavors USING btree (id);

CREATE UNIQUE INDEX protein_pkey ON public.proteins USING btree (id);

CREATE UNIQUE INDEX purchase_links_pkey ON public.sellers USING btree (id);

alter table "public"."flavors" add constraint "flavor_pkey" PRIMARY KEY using index "flavor_pkey";

alter table "public"."proteins" add constraint "protein_pkey" PRIMARY KEY using index "protein_pkey";

alter table "public"."sellers" add constraint "purchase_links_pkey" PRIMARY KEY using index "purchase_links_pkey";

alter table "public"."flavors" add constraint "flavors_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) not valid;

alter table "public"."flavors" validate constraint "flavors_product_id_fkey";

alter table "public"."flavors" add constraint "flavors_protein_id_fkey" FOREIGN KEY (protein_id) REFERENCES proteins(id) ON DELETE CASCADE not valid;

alter table "public"."flavors" validate constraint "flavors_protein_id_fkey";

alter table "public"."flavors" add constraint "flavors_review_id_fkey" FOREIGN KEY (review_id) REFERENCES reviews(id) not valid;

alter table "public"."flavors" validate constraint "flavors_review_id_fkey";

alter table "public"."flavors" add constraint "flavors_seller_id_fkey" FOREIGN KEY (seller_id) REFERENCES sellers(id) not valid;

alter table "public"."flavors" validate constraint "flavors_seller_id_fkey";

alter table "public"."sellers" add constraint "sellers_flavor_id_fkey" FOREIGN KEY (flavor_id) REFERENCES flavors(id) ON DELETE CASCADE not valid;

alter table "public"."sellers" validate constraint "sellers_flavor_id_fkey";

alter table "public"."products" add constraint "products_flavor_id_fkey" FOREIGN KEY (flavor_id) REFERENCES flavors(id) ON DELETE CASCADE not valid;

alter table "public"."products" validate constraint "products_flavor_id_fkey";

alter table "public"."proteins" add constraint "proteins_flavor_id_fkey" FOREIGN KEY (flavor_id) REFERENCES flavors(id) not valid;

alter table "public"."proteins" validate constraint "proteins_flavor_id_fkey";

alter table "public"."reviews" add constraint "reviews_flavor_id_fkey" FOREIGN KEY (flavor_id) REFERENCES flavors(id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_flavor_id_fkey";


