
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE TABLE "public"."facts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "summary" "text" DEFAULT ''::"text" NOT NULL,
    "usage" "text" DEFAULT ''::"text" NOT NULL,
    "protein_id" bigint NOT NULL
);

ALTER TABLE "public"."facts" OWNER TO "postgres";

ALTER TABLE "public"."facts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."facts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."features" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "protein_id" bigint NOT NULL
);

ALTER TABLE "public"."features" OWNER TO "postgres";

ALTER TABLE "public"."features" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."features_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."flavors" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" NOT NULL,
    "src" "text" NOT NULL,
    "protein_id" bigint NOT NULL,
    "seller_id" bigint,
    "product_id" bigint
);

ALTER TABLE "public"."flavors" OWNER TO "postgres";

ALTER TABLE "public"."flavors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."flavors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."makers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "src" "text" DEFAULT ''::"text" NOT NULL,
    "protein_id" bigint
);

ALTER TABLE "public"."makers" OWNER TO "postgres";

ALTER TABLE "public"."makers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."makers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."nutrients" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "quentity" "text" DEFAULT ''::"text" NOT NULL,
    "fact_id" bigint NOT NULL
);

ALTER TABLE "public"."nutrients" OWNER TO "postgres";

ALTER TABLE "public"."nutrients" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."nutrients_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."products" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "price" "text" DEFAULT ''::"text" NOT NULL,
    "capacity" "text" DEFAULT ''::"text" NOT NULL,
    "flavor_id" bigint
);

ALTER TABLE "public"."products" OWNER TO "postgres";

ALTER TABLE "public"."products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."proteins" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" NOT NULL,
    "src" "text" NOT NULL,
    "maker_id" bigint,
    "flavor_id" bigint
);

ALTER TABLE "public"."proteins" OWNER TO "postgres";

ALTER TABLE "public"."proteins" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proteins_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."sellers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "amazon" "text" DEFAULT ''::"text",
    "rakuten" "text" DEFAULT ''::"text",
    "yahoo" "text" DEFAULT ''::"text",
    "official" "text" DEFAULT ''::"text" NOT NULL,
    "flavor_id" bigint
);

ALTER TABLE "public"."sellers" OWNER TO "postgres";

ALTER TABLE "public"."sellers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sellers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."facts"
    ADD CONSTRAINT "facts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."features"
    ADD CONSTRAINT "features_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."flavors"
    ADD CONSTRAINT "flavors_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."makers"
    ADD CONSTRAINT "makers_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."nutrients"
    ADD CONSTRAINT "nutrients_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."proteins"
    ADD CONSTRAINT "proteins_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sellers"
    ADD CONSTRAINT "sellers_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."facts"
    ADD CONSTRAINT "facts_protein_id_fkey" FOREIGN KEY ("protein_id") REFERENCES "public"."proteins"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."features"
    ADD CONSTRAINT "features_protein_id_fkey" FOREIGN KEY ("protein_id") REFERENCES "public"."proteins"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."flavors"
    ADD CONSTRAINT "flavors_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id");

ALTER TABLE ONLY "public"."flavors"
    ADD CONSTRAINT "flavors_protein_id_fkey" FOREIGN KEY ("protein_id") REFERENCES "public"."proteins"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."flavors"
    ADD CONSTRAINT "flavors_seller_id_fkey" FOREIGN KEY ("seller_id") REFERENCES "public"."sellers"("id");

ALTER TABLE ONLY "public"."makers"
    ADD CONSTRAINT "makers_protein_id_fkey" FOREIGN KEY ("protein_id") REFERENCES "public"."proteins"("id");

ALTER TABLE ONLY "public"."nutrients"
    ADD CONSTRAINT "nutrients_fact_id_fkey" FOREIGN KEY ("fact_id") REFERENCES "public"."facts"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_flavor_id_fkey" FOREIGN KEY ("flavor_id") REFERENCES "public"."flavors"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."proteins"
    ADD CONSTRAINT "proteins_flavor_id_fkey" FOREIGN KEY ("flavor_id") REFERENCES "public"."flavors"("id");

ALTER TABLE ONLY "public"."proteins"
    ADD CONSTRAINT "proteins_maker_id_fkey" FOREIGN KEY ("maker_id") REFERENCES "public"."makers"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."sellers"
    ADD CONSTRAINT "sellers_flavor_id_fkey" FOREIGN KEY ("flavor_id") REFERENCES "public"."flavors"("id") ON DELETE CASCADE;

ALTER TABLE "public"."facts" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."nutrients" ENABLE ROW LEVEL SECURITY;


GRANT ALL ON TABLE "pgsodium"."decrypted_key" TO "pgsodium_keyholder";

GRANT ALL ON TABLE "pgsodium"."masking_rule" TO "pgsodium_keyholder";

GRANT ALL ON TABLE "pgsodium"."mask_columns" TO "pgsodium_keyholder";

GRANT ALL ON TABLE "public"."facts" TO "anon";
GRANT ALL ON TABLE "public"."facts" TO "authenticated";
GRANT ALL ON TABLE "public"."facts" TO "service_role";

GRANT ALL ON SEQUENCE "public"."facts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."facts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."facts_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."features" TO "anon";
GRANT ALL ON TABLE "public"."features" TO "authenticated";
GRANT ALL ON TABLE "public"."features" TO "service_role";

GRANT ALL ON SEQUENCE "public"."features_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."features_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."features_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."flavors" TO "anon";
GRANT ALL ON TABLE "public"."flavors" TO "authenticated";
GRANT ALL ON TABLE "public"."flavors" TO "service_role";

GRANT ALL ON SEQUENCE "public"."flavors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."flavors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."flavors_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."makers" TO "anon";
GRANT ALL ON TABLE "public"."makers" TO "authenticated";
GRANT ALL ON TABLE "public"."makers" TO "service_role";

GRANT ALL ON SEQUENCE "public"."makers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."makers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."makers_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."nutrients" TO "anon";
GRANT ALL ON TABLE "public"."nutrients" TO "authenticated";
GRANT ALL ON TABLE "public"."nutrients" TO "service_role";

GRANT ALL ON SEQUENCE "public"."nutrients_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."nutrients_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."nutrients_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";

GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."proteins" TO "anon";
GRANT ALL ON TABLE "public"."proteins" TO "authenticated";
GRANT ALL ON TABLE "public"."proteins" TO "service_role";

GRANT ALL ON SEQUENCE "public"."proteins_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proteins_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proteins_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."sellers" TO "anon";
GRANT ALL ON TABLE "public"."sellers" TO "authenticated";
GRANT ALL ON TABLE "public"."sellers" TO "service_role";

GRANT ALL ON SEQUENCE "public"."sellers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sellers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sellers_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
