
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE "public"."flavors " (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "protein_id" bigint NOT NULL,
    "review_id" bigint,
    "src" "text" DEFAULT ''::"text" NOT NULL,
    "product_id" bigint,
    "purchase_link_id" bigint
);

ALTER TABLE "public"."flavors " OWNER TO "postgres";

ALTER TABLE "public"."flavors " ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."flavors _id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."makers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "src" "text" NOT NULL,
    "protein_id" bigint
);

ALTER TABLE "public"."makers" OWNER TO "postgres";

ALTER TABLE "public"."makers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."makers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."products" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "price" "text" DEFAULT ''::"text" NOT NULL,
    "capacity" "text" DEFAULT ''::"text" NOT NULL,
    "flavor_id" bigint NOT NULL
);

ALTER TABLE "public"."products" OWNER TO "postgres";

ALTER TABLE "public"."products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."proteins" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "maker_id" bigint NOT NULL,
    "flavor_id" bigint,
    "src" "text" DEFAULT ''::"text" NOT NULL
);

ALTER TABLE "public"."proteins" OWNER TO "postgres";

ALTER TABLE "public"."proteins" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proteins_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."purchase_links" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "amazon" "text" DEFAULT ''::"text",
    "yahoo" "text" DEFAULT ''::"text",
    "official" "text" DEFAULT ''::"text" NOT NULL,
    "flavor_id" bigint NOT NULL,
    "rakuten" "text" DEFAULT ''::"text"
);

ALTER TABLE "public"."purchase_links" OWNER TO "postgres";

ALTER TABLE "public"."purchase_links" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."purchase_links_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE "public"."reviews" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "title" "text" DEFAULT ''::"text" NOT NULL,
    "description" "text" DEFAULT ''::"text" NOT NULL,
    "rate" bigint NOT NULL,
    "flavor_id" bigint NOT NULL
);

ALTER TABLE "public"."reviews" OWNER TO "postgres";

ALTER TABLE "public"."reviews" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reviews_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."flavors "
    ADD CONSTRAINT "flavors _pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."makers"
    ADD CONSTRAINT "makers_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."makers"
    ADD CONSTRAINT "makers_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."proteins"
    ADD CONSTRAINT "proteins_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."purchase_links"
    ADD CONSTRAINT "purchase_links_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."flavors "
    ADD CONSTRAINT "flavors _product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id");

ALTER TABLE ONLY "public"."flavors "
    ADD CONSTRAINT "flavors _protein_id_fkey" FOREIGN KEY ("protein_id") REFERENCES "public"."proteins"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."flavors "
    ADD CONSTRAINT "flavors _purchase_link_id_fkey" FOREIGN KEY ("purchase_link_id") REFERENCES "public"."purchase_links"("id");

ALTER TABLE ONLY "public"."flavors "
    ADD CONSTRAINT "flavors _review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "public"."reviews"("id");

ALTER TABLE ONLY "public"."makers"
    ADD CONSTRAINT "makers_protein_id_fkey" FOREIGN KEY ("protein_id") REFERENCES "public"."proteins"("id");

ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_flavor_id_fkey" FOREIGN KEY ("flavor_id") REFERENCES "public"."flavors "("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."proteins"
    ADD CONSTRAINT "proteins_flavor_id_fkey" FOREIGN KEY ("flavor_id") REFERENCES "public"."flavors "("id");

ALTER TABLE ONLY "public"."proteins"
    ADD CONSTRAINT "proteins_maker_id_fkey" FOREIGN KEY ("maker_id") REFERENCES "public"."makers"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."purchase_links"
    ADD CONSTRAINT "purchase_links_flavor_id_fkey" FOREIGN KEY ("flavor_id") REFERENCES "public"."flavors "("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_flavor_id_fkey" FOREIGN KEY ("flavor_id") REFERENCES "public"."flavors "("id") ON DELETE CASCADE;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."flavors " TO "anon";
GRANT ALL ON TABLE "public"."flavors " TO "authenticated";
GRANT ALL ON TABLE "public"."flavors " TO "service_role";

GRANT ALL ON SEQUENCE "public"."flavors _id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."flavors _id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."flavors _id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."makers" TO "anon";
GRANT ALL ON TABLE "public"."makers" TO "authenticated";
GRANT ALL ON TABLE "public"."makers" TO "service_role";

GRANT ALL ON SEQUENCE "public"."makers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."makers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."makers_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";

GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."proteins" TO "anon";
GRANT ALL ON TABLE "public"."proteins" TO "authenticated";
GRANT ALL ON TABLE "public"."proteins" TO "service_role";

GRANT ALL ON SEQUENCE "public"."proteins_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proteins_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proteins_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."purchase_links" TO "anon";
GRANT ALL ON TABLE "public"."purchase_links" TO "authenticated";
GRANT ALL ON TABLE "public"."purchase_links" TO "service_role";

GRANT ALL ON SEQUENCE "public"."purchase_links_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."purchase_links_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."purchase_links_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."reviews" TO "anon";
GRANT ALL ON TABLE "public"."reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."reviews" TO "service_role";

GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
