alter table "public"."レビュー" drop constraint "レビュー_id_key";

alter table "public"."レビュー" drop constraint "レビュー_protein_id_fkey";

alter table "public"."レビュー" drop constraint "レビュー_pkey";

drop index if exists "public"."レビュー_id_key";

drop index if exists "public"."レビュー_pkey";

drop table "public"."レビュー";

create table "public"."reviews" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null default ''::text,
    "rate" numeric not null default '0'::numeric,
    "title" text not null default ''::text,
    "description" text not null,
    "protein_id" bigint not null
);


alter table "public"."reviews" enable row level security;

CREATE UNIQUE INDEX "レビュー_id_key" ON public.reviews USING btree (id);

CREATE UNIQUE INDEX "レビュー_pkey" ON public.reviews USING btree (id);

alter table "public"."reviews" add constraint "レビュー_pkey" PRIMARY KEY using index "レビュー_pkey";

alter table "public"."reviews" add constraint "reviews_protein_id_fkey" FOREIGN KEY (protein_id) REFERENCES proteins(id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_protein_id_fkey";

alter table "public"."reviews" add constraint "レビュー_id_key" UNIQUE using index "レビュー_id_key";


