create table "public"."reviews" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null default ''::text,
    "title" text not null default ''::text,
    "description" text not null default ''::text,
    "rate" bigint not null,
    "flavor_id" bigint not null
);


CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (id);

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."reviews" add constraint "reviews_flavor_id_fkey" FOREIGN KEY (flavor_id) REFERENCES flavors(id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_flavor_id_fkey";


