name: Build Test
on:
  push:
    branches-ignore:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      uses: actions/checkout@v3.0.2

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 18.10.0

      - name: Get node_modules cache
      uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}

      - name: Install dependencies
        run: yarn install

      - name: Check yarn.lock
        run: '! git diff --name-only | grep yarn.lock'

      - name: Run lint
        run: yarn lint

      - name: Build
        run: yarn build
