name: Build Test
on:
  push:
    branches-ignore:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 18.10.0

      - run: yarn install
      - run: yarn lint
      - run: yarn build
